# Generated by Django 3.1 on 2020-09-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('pubdate', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.person')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dass21', models.IntegerField(choices=[(0, 'Never'), (1, 'Sometimes'), (2, 'Often'), (3, 'Almost Always')], null=True)),
                ('ders', models.IntegerField(choices=[(1, 'Almost Never'), (2, 'Sometimes'), (3, 'About Half The Time'), (4, 'Most Of The Time'), (5, 'Almost Always')], null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tests.question')),
            ],
        ),
    ]
